### ISSUE TITLE
recursive callstack bug

### ISSUE THREAD

**Issue by vrnmthr** [vrnmthr/online-contact#12]
sometimes, this error randomly happens. I would guess that it's because we're trying to send a socket over a socket?? or something silly like that. look it up.

```
internal/bootstrap/pre_execution.js:304
    get() {
       ^

RangeError: Maximum call stack size exceeded
    at get (internal/bootstrap/pre_execution.js:304:8)
    at hasBinary (/Users/vrnmthr/Source/online-contact/server/node_modules/has-binary2/index.js:44:3)
    at hasBinary (/Users/vrnmthr/Source/online-contact/server/node_modules/has-binary2/index.js:58:59)
    at hasBinary (/Users/vrnmthr/Source/online-contact/server/node_modules/has-binary2/index.js:58:59)
    at hasBinary (/Users/vrnmthr/Source/online-contact/server/node_modules/has-binary2/index.js:58:59)
    at hasBinary (/Users/vrnmthr/Source/online-contact/server/node_modules/has-binary2/index.js:58:59)
    at hasBinary (/Users/vrnmthr/Source/online-contact/server/node_modules/has-binary2/index.js:58:59)
    at hasBinary (/Users/vrnmthr/Source/online-contact/server/node_modules/has-binary2/index.js:58:59)
    at hasBinary (/Users/vrnmthr/Source/online-contact/server/node_modules/has-binary2/index.js:58:59)
    at hasBinary (/Users/vrnmthr/Source/online-contact/server/node_modules/has-binary2/index.js:58:59)
```

**Comment by el-naza** [comment]
Just had the same problem today. I was trying to send `io.sockets` over a socket

**Comment by adengopaul** [comment]
So how do you solve it?
